# Generated by Django 5.1.1 on 2025-03-09 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('mc-quest', 'Multiple Choice'), ('float-num-quest', 'Float Number'), ('one-line-text-quest', 'One Line Text'), ('manylines-text-quest', 'Many Lines Text'), ('graphing-quest', 'Graphing')], default='mc-quest', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='ref',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_type', models.CharField(max_length=50)),
                ('ref_value', models.CharField(max_length=300)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='hw01.question')),
            ],
            options={
                'db_table': 'hw01_reference',
            },
        ),
    ]
