# Generated by Django 5.0.1 on 2025-03-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw01', '0002_question_qtype_question_ref_alter_question_question_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reference',
            new_name='Ref',
        ),
    ]
