# Generated by Django 5.0.1 on 2025-03-10 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw01', '0004_rename_ref_question_references_alter_ref_question'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ref',
            table='hw01_ref',
        ),
    ]
