# Generated by Django 5.1.1 on 2025-03-08 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp2', '0002_alter_questionoption_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizapp2_options', to='quizapp2.question'),
        ),
        migrations.AlterModelTable(
            name='question',
            table='quizapp2_question',
        ),
        migrations.AlterModelTable(
            name='questionoption',
            table='quizapp2_questionoption',
        ),
        migrations.AlterModelTable(
            name='student',
            table='quizapp2_student',
        ),
    ]
