# Generated by Django 5.1.1 on 2025-03-09 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp2', '0003_alter_questionoption_question_alter_question_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quizapp2.question'),
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
        migrations.AlterModelTable(
            name='questionoption',
            table='questionoption',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
