# Generated by Django 5.0.1 on 2025-03-10 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw01', '0003_rename_reference_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ref',
            new_name='references',
        ),
        migrations.AlterField(
            model_name='ref',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refs', to='hw01.question'),
        ),
    ]
